## https://rust-lang.github.io/rustfmt/
## nightly build features are marked with a #

combine_control_expr = false #
condense_wildcard_suffixes = true #
format_code_in_doc_comments = true #
format_strings = true #
hard_tabs = true
imports_layout = "HorizontalVertical" #
match_arm_blocks = false #
match_block_trailing_comma = true #
normalize_comments = true #
overflow_delimited_expr = true #
reorder_impl_items = true #
use_field_init_shorthand = true
wrap_comments = true #
