os: windows
language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose

cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
