language: rust
os: windows
rust:
    - stable
    - beta
    - nightly

script:
    - cargo build --verbose
    - cargo test --verbose

cache: cargo
jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true
